# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:             [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
timezone: America/New_York
excerpt_separator: <!--more-->
google_analytics: UA-81686781-1
title:            .milk
tagline:          My Infinite Lack of Knowledge
description:      Self-Documenting Self
url:              https://cheshirecatalyst.github.io
baseurl:          /

author:
  name:           'Seth Price'
  url:            https://github.com/cheshirecatalyst

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:
