# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:             [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            MILK
tagline:          My Infinite Lack of Knowledge
description:      "A blog demonstrating my infinite lack of knowledge."
url:              https://cheshirecatalyst.github.io
baseurl:          /

author:
  name:           'Seth Price'
  url:            https://github.com/cheshirecatalyst

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:
